ALTER TABLE "bracelets"
ADD COLUMN IF NOT EXISTS "dernier_signal_le" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "derniere_position_le" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "statut_connexion" TEXT;

ALTER TABLE "positions_gps"
ADD COLUMN IF NOT EXISTS "porteur_externe_id" TEXT,
ADD COLUMN IF NOT EXISTS "precision_m" DECIMAL,
ADD COLUMN IF NOT EXISTS "accuracy_meters" INTEGER,
ADD COLUMN IF NOT EXISTS "zone_externe_id" TEXT,
ADD COLUMN IF NOT EXISTS "zone_status" TEXT,
ADD COLUMN IF NOT EXISTS "battery_pct" INTEGER,
ADD COLUMN IF NOT EXISTS "gprs_signal" INTEGER,
ADD COLUMN IF NOT EXISTS "gps_satellites" INTEGER,
ADD COLUMN IF NOT EXISTS "gps_lost" BOOLEAN,
ADD COLUMN IF NOT EXISTS "gprs_lost" BOOLEAN,
ADD COLUMN IF NOT EXISTS "raw_payload" JSONB;
